game.create:
  path: /api/games
  controller: 'game.api.home.controller::createAction'
  method: ['post']

game.view:
  path: /api/games/{uuid}
  controller: 'game.api.home.controller::viewAction'
  method: ['get']
  before: ['middleware.game.exists']

game.attack:
  path: /api/games/{uuid}/attack
  controller: 'game.api.home.controller::viewAction'
  method: ['get']
  before: ['middleware.game.exists']