game.homepage:
  path: /games
  controller: 'game.home.controller'
  action: 'indexAction'
  method: GET

game.create:
  path: /api/games
  controller: 'game.api.home.controller'
  action: 'createAction'
  method: POST