version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: castle-game-webserver
    working_dir: /application
    volumes:
        - .:/application
        - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "9090:80"

  php-fpm:
    build: .docker/php-fpm
    container_name: castle-game-php-fpm
    working_dir: /
    volumes:
      - .:/application
      - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

