game.homepage:
    path: /game
    controller: 'game.home.controller'
    action: 'indexAction'
    method: GET

game.test:
    path: /game/test
    controller: 'game.home.controller'
    action: 'testAction'
    method: GET